name: 🚀 AutoPub Release
concurrency: release

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  check-release:
    name: 📦 Check for release
    runs-on: ubuntu-latest
    outputs:
      has_release: ${{ steps.check.outputs['has-release'] }}
    env:
      TYPEFULLY_API_KEY: ${{ secrets.TYPEFULLY_API_KEY }}
      TYPEFULLY_SOCIAL_SET_ID: ${{ secrets.TYPEFULLY_SOCIAL_SET_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Check for release
        id: check
        uses: autopub/autopub-action@v1.1.0
        with:
          command: check
          autopub-version: "1.0.0a58"
          github-token: ${{ secrets.BOT_TOKEN }}
          extra-plugins: "strawberry-autopub-plugins==0.1.0"

      - name: Debug info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "has_release: ${{ steps.check.outputs['has-release'] }}"

  publish:
    name: 📦 Publish to PyPI
    needs: check-release
    if: ${{ github.ref == 'refs/heads/main' && needs.check-release.outputs.has_release == 'true' }}
    runs-on: ubuntu-latest
    env:
      TYPEFULLY_API_KEY: ${{ secrets.TYPEFULLY_API_KEY }}
      TYPEFULLY_SOCIAL_SET_ID: ${{ secrets.TYPEFULLY_SOCIAL_SET_ID }}

    steps:
      - name: Debug info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "has_release: ${{ needs.check-release.outputs.has_release }}"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Prepare release
        uses: autopub/autopub-action@v1.1.0
        with:
          command: prepare
          autopub-version: "1.0.0a58"
          extra-plugins: "strawberry-autopub-plugins==0.1.0"

      - name: Build package
        uses: autopub/autopub-action@v1.1.0
        with:
          command: build
          autopub-version: "1.0.0a58"
          extra-plugins: "strawberry-autopub-plugins==0.1.0"

      - name: Publish to PyPI
        uses: autopub/autopub-action@v1.1.0
        with:
          command: publish
          autopub-version: "1.0.0a58"
          github-token: ${{ secrets.BOT_TOKEN }}
          git-username: botberry
          git-email: bot@strawberry.rocks
          extra-plugins: "strawberry-autopub-plugins==0.1.0"
